#!/bin/python3

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def is_even(num):
    if num % 2 == 0:
        return True
    return False

def fibo(limit):
    # return a list of fibonacci numbers stopping at the last fibonacci number below 'limit'. 
    # assume good input and a limit higher than 2.
    fib = [1, 2]
    while True:
        next_num = fib[-1] + fib[-2] 
        if next_num >= limit:
            return fib
        fib.append(next_num)

ans = 0
fib = fibo(4000000)
for term in fib:
    if is_even(term):
        ans += term
print(ans)
